- name: play level variables
  hosts: localhost
  vars:
    URL: "sample.example.com"
  tasks:
    - ansible.builtin.debug:
        msg: url = {{ URL }}

- name: task level variables
  hosts: localhost
  tasks:
    - vars:
        URL: "task.example.com"
      ansible.builtin.debug:
        msg: url = {{ URL }}

- name: file level variables
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - ansible.builtin.debug:
        msg: url = {{ URL }}

- name: inventory level variables
  hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: url = {{ URL }}

- name: extract url
  debug:
    msg: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz




