- name: play level variables
  hosts: localhost
  vars:
    URL: "sample.example.com"
  tasks:
    - ansible.builtin.debug:
        msg: url = {{ URL }}

- name: task level variables
  hosts: localhost
  tasks:
    vars:
      URL: "task.example.com"
    - ansible.builtin.debug:
        msg: url = {{ URL }}


