- name: register a variable
  hosts: localhost
  tasks:
    - name: shell command
      ansible.builtin.shell: uptime
      register: purna

    - ansible.builtin.debug:
        msg: "{{ purna }}"

    - ansible.builtin.set_fact:
        status: "{{ purna.cmd }}"

    - ansible.builtin.debug:
        msg: "{{ status }}"
