- name: concept
  hosts: localhost
  tasks:
    - debug:
        msg: fruit name - {{ item }}
      loop:
        - apple
        - banana

- hosts:
  tasks:
    - debug:
        msg: fruit name - {{ item.name }}, {{ item.quantity }}
      loop:
        - { name:"apple", quantity:5 }
        - { name:"guva", quantity:5 }





