- name: concept
  hosts: localhost
  tasks:
    - debug:
        msg: fruit name - {{ item }}
      loop:
        - apple
        - banana

- hosts: localhost
  tasks:
    - debug:
        msg: fruit name - {{ item.name }}, {{ item.quantity }}
      loop:
        - { name: "apple", quantity: 5 }
        - { name: "banana", quantity: 5 }





