- name: cut the url
  hosts: localhost
  tasks:
    - name: filter
      debug:
        msg: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz